##############################################################################
# GitHub Actions Workflow for Boost.Json
#
# Copyright (c) 2020 Mateusz Loskot <mateusz@loskot.net>
#
# Use, modification and distribution is subject to the Boost Software License,
# Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)
##############################################################################
name: cmake-standalone

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Uninstall Boost
        run: |
          sudo apt-get remove -y -q --purge libboost-all-dev libboost-doc libboost-tools-dev 
          sudo apt-get autoremove -y -q
          sudo apt-get autoclean -y -q

      - uses: actions/checkout@v2
 
      - name: CMake
        run: |
          cmake -B "$GITHUB_WORKSPACE/build" -DCMAKE_VERBOSE_MAKEFILE=ON -DBOOST_JSON_STANDALONE=ON
      
      - name: Build
        run: |
          cmake --build "$GITHUB_WORKSPACE/build" --config Release

      - name: Test
        run: |
          cd "$GITHUB_WORKSPACE/build"
          ctest --build-config Release --output-on-failure
