name: analyze-bloat

on: [push, pull_request]

env:
  cmake-config-opts: '-DBOOST_JSON_STANDALONE=ON -DBOOST_JSON_BUILD_TESTS=OFF -DBOOST_JSON_BUILD_FUZZERS=OFF -DBOOST_JSON_BUILD_BENCHMARKS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-fvisibility=hidden"'

jobs:
  analyze-bloat:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch head
        uses: actions/checkout@v2
        with:
          path: 'head_ref'
      - name: Compile static lib for head ref
        run: |
          echo ${{ github.event_name }}
          cmake -Hhead_ref -Bhead_ref/build ${{ env.cmake-config-opts }}
          cmake --build head_ref/build
      - name: Bloat analysis - absolute values
        uses: djarek/bloaty-analyze@v1.0.0
        with:
          file: head_ref/build/libboost_json.a
          rows: 0 # 0 indicates unlimited number of rows
      - name: Fetch base
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
          path: 'base_ref'
      - name: Compile static lib for base ref
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          cmake -Hbase_ref -Bbase_ref/build ${{ env.cmake-config-opts }}
          cmake --build base_ref/build
      - name: Bloat analysis - diff
        uses: djarek/bloaty-analyze@v1.0.0
        if: ${{ github.event_name == 'pull_request' }}
        with:
          file: head_ref/build/libboost_json.a
          base-file: base_ref/build/libboost_json.a
          rows: 0 # 0 indicates unlimited number of rows
